---
# tasks file for create-user
- name: Create user ansible
  win_user: 
    name: ansible
    password: Password123
    state: present
  become: yes  
  ignore_errors: yes
  register: result

- name: Add user to the group if not already a member
  win_command: 'net localgroup "Administrators" ansible /add'
  become: yes
  when: "'The specified account name is already a member of the group.' not in results.stderr"